**Importing the neccessary libraries**

In [1]:
import os
import pandas as pd
import seaborn as sns

**Loading the Data for 1 subject**

In [2]:
subjectwise_data_folder = 'subjectwise_data'
def load_candidate_data(candidate_id):
    candidate_folder = os.path.join(subjectwise_data_folder, str(candidate_id))

    #loading emotion data
    emotion_df = pd.read_csv(os.path.join(candidate_folder, "emotion.csv"))

    #loading gaze data
    gaze_df = pd.read_csv(os.path.join(candidate_folder, "gaze.csv"))

    #loading metadata
    metadata_df = pd.read_csv(os.path.join(candidate_folder, "metadata.csv"))

    #loading transcript data
    transcript_score_df = pd.read_csv(os.path.join(candidate_folder, f"{candidate_id}.csv"))

    #loading transcript
    with open(os.path.join(candidate_folder, f"{candidate_id}.txt"), 'r') as file:
        transcript_text = file.read()
    
    return emotion_df, gaze_df, metadata_df, transcript_score_df, transcript_text

In [3]:
#loading data for candidate 1
candidate_id = 1
emotion_data, gaze_data, metadata_data, transcript_scores, transcript_text = load_candidate_data(candidate_id)

**Understanding each data step by step**

Emotion Data

In [5]:
emotion_data

,movie_id,image_seq,angry,disgust,fear,happy,sad,surprise,neutral,dominant_emotion
0,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,0,4.31735,0.000594,2.879790,1.650350,2.779980,0.600814,87.77110,neutral
1,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,1,53.22530,2.981640,12.736800,1.523470,1.051320,27.216800,1.26462,angry
2,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,2,8.79651,0.029468,2.968160,16.831500,39.884600,0.279335,31.21050,sad
3,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,3,9.45303,0.106778,1.553080,20.930100,3.503870,0.909426,63.54370,neutral
4,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,4,56.00020,0.000004,0.162231,5.583580,0.197026,12.807600,25.24940,angry
...,...,...,...,...,...,...,...,...,...,...
82,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,90,1.57152,0.097637,6.366870,14.010700,37.502900,1.376500,39.07380,neutral
83,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,91,2.27476,0.030632,14.994900,4.768020,8.165430,0.970922,68.79540,neutral
84,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,92,4.32456,0.000002,3.714960,0.000036,90.418700,0.000008,1.54175,sad
85,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,93,11.03230,0.000001,6.368120,0.003859,51.579600,0.019682,30.99640,sad
86,93663f94-bf0a-4ce8-a29a-a5236cc7fe6a,94,19.82640,0.000431,0.196329,0.768515,0.062035,48.557100,30.58920,surprise

In [6]:
emotion_data.shape

(87, 10)

In [7]:
emotion_data.describe()

,image_seq,angry,disgust,fear,happy,sad,surprise,neutral
count,87.000000,87.000000,8.700000e+01,87.000000,87.000000,87.000000,87.000000,87.000000
mean,45.390805,14.451059,6.168965e-01,18.382797,5.865318,13.575324,8.744969,38.363648
std,27.587643,18.544205,2.679399e+00,25.073562,11.237819,19.787221,19.621163,33.468718
min,0.000000,0.164384,2.400910e-10,0.079219,0.000005,0.000073,0.000008,0.000117
25%,22.500000,1.867450,8.769180e-05,1.862945,0.143215,1.845405,0.210637,8.035385
50%,44.000000,6.412790,3.443590e-03,6.366870,1.476330,5.578010,0.970922,28.221400
75%,68.500000,18.765500,6.486260e-02,21.010100,5.569355,14.056700,6.524355,71.227450
max,94.000000,71.172500,2.150890e+01,94.981800,66.222300,91.563600,97.834400,97.823000

In [9]:
emotion_data.nunique()

movie_id             1
image_seq           87
angry               87
disgust             87
fear                87
happy               87
sad                 87
surprise            87
neutral             87
dominant_emotion     6
dtype: int64

In [13]:
#checking unique values in the 'dominant_emotion' column
print(emotion_data['dominant_emotion'].unique())

#counting occurrences of each dominant emotion
print(emotion_data['dominant_emotion'].value_counts())

['neutral' 'angry' 'sad' 'fear' 'surprise' 'happy']
dominant_emotion
neutral     37
fear        19
angry       11
sad         10
surprise     7
happy        3
Name: count, dtype: int64

Gaze Data

In [15]:
gaze_data

                                movie_id  image_seq  gaze  blink  eye_offset
0   93663f94-bf0a-4ce8-a29a-a5236cc7fe6a          1     1      0      6.2253
1   93663f94-bf0a-4ce8-a29a-a5236cc7fe6a          2     1      0     22.7274
2   93663f94-bf0a-4ce8-a29a-a5236cc7fe6a          3     1      0      2.5704
3   93663f94-bf0a-4ce8-a29a-a5236cc7fe6a          4     1      0     21.1097
4   93663f94-bf0a-4ce8-a29a-a5236cc7fe6a          5     1      0      1.8453
..                                   ...        ...   ...    ...         ...
83  93663f94-bf0a-4ce8-a29a-a5236cc7fe6a         91     1      0     19.5787
84  93663f94-bf0a-4ce8-a29a-a5236cc7fe6a         92     1      0     22.9742
85  93663f94-bf0a-4ce8-a29a-a5236cc7fe6a         93     1      0     24.1476
86  93663f94-bf0a-4ce8-a29a-a5236cc7fe6a         94     1      0     -2.2199
87  93663f94-bf0a-4ce8-a29a-a5236cc7fe6a         95     1      0     23.6015

[88 rows x 5 columns]

**Calculating eye contact consistency**

In [16]:
# Calculate percentage of eye contact
eye_contact_percentage = normalized_gaze_data['gaze'].mean() * 100
print(f"Eye Contact Consistency: {eye_contact_percentage:.2f}%")

NameError: name 'data' is not defined